# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ovhmanager',
                'doc_host': 'https://hassoun.github.io',
                'git_url': 'https://github.com/hassoun/ovhmanager',
                'lib_path': 'ovhmanager'},
  'syms': {'ovhmanager.core': {'ovhmanager.core.foo': ('core.html#foo', 'ovhmanager/core.py')}}}
